    <h1>Add form</h1>
    
    <?php
    $form = $this->form;
    //$form->setAttribute('action', $this->url('modules/add'));
    $form->prepare();
    ?>
    
    <?php echo $this->form()->openTag($form);?>
		<fieldset>
		    <legend><?php echo $form->getName()?></legend>
		    <?php foreach ($form as $element) {?>
		    	<label><?php //echo $element->getLabel()?></label>
		    	<?php if($element->getMessages()){?>
		    	<div class="alert alert-error">
				  <button type="button" class="close" data-dismiss="alert">&times;</button>
				  <?php echo join("<br />", $element->getMessages())?>
				</div>
				<?php }?>
				<?php echo $this->formRow($element)?>
			<?php }?>
	    	<br />
			<button type="submit" class="btn btn-primary">Submit</button>
		</fieldset>
	<?php echo $this->form()->closeTag();?>

    <?php
    /*
    $form = $this->form;
    $form->setAttribute('action', $this->url('modules'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();*/
    ?>