    <h1>Edit form</h1>
    
    <ul>
    	<li><a href="#">Main sheet</a></li>
	    <?php foreach($this->form->getOption('sheets') as $sheet){?>
	    	<li><a href="<?php echo $this->url('modules/edit/sheet', array('name' => 'Test', 'id' => 15, 'sheet_name' => 'sheet'))?>"><?php echo $sheet->getLabel()?></a></li>
	    <?php }?>
    </ul>
		    
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('modules'));
    $form->prepare();
    ?>
    
    <?php echo $this->form()->openTag($form);?>
		<fieldset>
		    <legend><?php echo $form->getName()?></legend>
		    
		    <?php foreach ($form as $element) {?>
		    	<label><?php //echo $element->getLabel()?></label>
		    	<?php if($element->getMessages()){?>
		    	<div class="alert alert-error">
				  <button type="button" class="close" data-dismiss="alert">&times;</button>
				  <?php echo join("<br />", $element->getMessages())?>
				</div>
				<?php }?>
				<?php echo $this->formRow($element)?>
			<?php }?>
	    	<br />
			<button type="submit" class="btn btn-primary">Save</button>
		</fieldset>
	<?php echo $this->form()->closeTag();?>

    <?php
    /*
    $form = $this->form;
    $form->setAttribute('action', $this->url('modules'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();*/
    ?>