    <h1><?php echo $this->form->getName()?></h1>

    <ul class="nav nav-pills">
		<li class="active">
			<a href="#">Main sheet</a>
		</li>
		<?php foreach($this->form->getOption('sheets') as $sheet){?>
	    	<li><a href="<?php echo $this->url('modules/edit/sheet', array('name' => $this->name, 'id' => $this->id, 'sheet_name' => $sheet->getName()))?>"><?php echo $sheet->getLabel()?></a></li>
	    <?php }?>
	</ul>

    <?php
    $form = $this->form;
    $form->prepare();
    ?>

    <?php echo $this->form()->openTag($form);?>
		<fieldset>
			<legend><?php echo $form->getName()?></legend>

			<?php foreach ($form as $element) {?>
				<label><?php echo $element->getLabel()?></label>
				<?php echo $this->formElement($element)?>
				<?php if($element->getOption('blockHelp')){?>
					<span class="help-block"><?php echo $element->getOption('blockHelp')?></span>
				<?php }?>
			<?php }?>

			<br /><br />
			<button type="submit" class="btn btn-primary">Save</button>

	  </fieldset>
	<?php echo $this->form()->closeTag();?>

    <?php
    /*
    $form = $this->form;
    $form->setAttribute('action', $this->url('modules'));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();*/
    ?>