<h1>List of modules</h1>

<a href="#" class="btn btn-info btn-small"><i class="icon-plus"></i> Add new module</a>

<br /><br />

<table class="table table-bordered">

	<thead>
		<tr>
			<th>Module name</th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<tbody>

		<?php foreach($this->moduleList() as $module){?>
		<tr>
			<td><?php echo $module->module_name?></td>
			<td><a href="#" class="btn btn-warning btn-mini"><i class="icon-pencil"></i> Edit</a></td>
			<td><a href="#" class="btn btn-danger btn-mini"><i class="icon-remove"></i> Delete</a></td>
		</tr>
		<?php }?>

	</tbody>

</table>

<a href="#" class="btn btn-info btn-small"><i class="icon-plus"></i> Add new module</a>