    <h1>Edit form</h1>
    
    <ul class="nav nav-pills">
		<li>
			<a href="<?php echo $this->url('modules/edit', array('name' => $this->parentEntityName, 'id' => $this->id))?>">Main sheet</a>
		</li>
		<?php foreach($this->formParent->getOption('sheets') as $sheet){?>
	    	<li <?php if($this->sheetName==$sheet->getName()){?>class="active"<?php }?>><a href="<?php echo $this->url('modules/edit/sheet', array('name' => $this->parentEntityName, 'id' => $this->id, 'sheet_name' => $sheet->getName()))?>"><?php echo $sheet->getLabel()?></a></li>
	    <?php }?>
	</ul>
    
    <?php if(count($this->flashMessages)) : ?>
	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<?php foreach ($this->flashMessages as $msg) : ?>
	    	<strong>Well done!</strong> <?php echo $msg; ?><br />
	    <?php endforeach; ?>
	</div>
	<?php endif; ?>
    
    <?php foreach($this->data as $item){?>
    
	    <?php
	    $form = $this->form;
	    $form->bind($item);
	    $form->setAttribute('action', $this->url('modules'));
	    $form->prepare();
	    ?>
	    
	    <?php echo $this->form()->openTag($form);?>
			<fieldset>
			    <legend><?php echo $form->getName()?></legend>
			    <?php foreach ($form as $element) {?>
			    	<label><?php //echo $element->getLabel()?></label>
			    	<?php if($element->getMessages()){?>
			    	<div class="alert alert-error">
					  <button type="button" class="close" data-dismiss="alert">&times;</button>
					  <?php echo join("<br />", $element->getMessages())?>
					</div>
					<?php }?>
					<?php echo $this->formRow($element)?>
				<?php }?>
		    	<br />
				<button type="submit" class="btn btn-primary">Save</button>
			</fieldset>
		<?php echo $this->form()->closeTag();?>

   <?php }?>
   
   <h1>Add new entity to sheet</h1>
   
   <?php
    $form = $this->form;
    $form->setAttribute('action', null);
    $form->bind(new $this->entity);
    $form->prepare();
    ?>
    
    <?php echo $this->form()->openTag($form);?>
		<fieldset>
		    <legend><?php echo $form->getName()?></legend>
		    <?php foreach ($form as $element) {?>
		    	<label><?php //echo $element->getLabel()?></label>
		    	<?php if($element->getMessages()){?>
		    	<div class="alert alert-error">
				  <button type="button" class="close" data-dismiss="alert">&times;</button>
				  <?php echo join("<br />", $element->getMessages())?>
				</div>
				<?php }?>
				<?php echo $this->formRow($element)?>
			<?php }?>
	    	<br />
			<button type="submit" class="btn btn-primary">Save</button>
		</fieldset>
	<?php echo $this->form()->closeTag();?>