<h1>Dashboard</h1>

<p>
	Add event for dashboard load to easily modify it.
</p>

<p>
	Other TODOS:
	<ul>
		<li>Add redactor ad wysiwyg</li>
		<li>Delete rows with confirmation</li>
		<li>Add and edit modules</li>
		<li>Files and pictures</li>
		<li>Form design</li>
		<li>User ACL management</li>
		<li>Relations check before delete</li>
		<li>Relations show next to entity</li>
		<li>Cyclic sheet entity management</li>
		<li>Label newly added entities with bootstrap label | Set custom data to flash messanger</li>
		<li>URL management as separate table with URLS and specialized data type url. Allow just one url datatype per module. Check if url exists. Cascade delete upon module item deletion. Inject to navigation helpers.</li>
		<li>Sort by related fields</li>
		<li>Add filters</li>
	</ul>
</p>