<div style="text-align: center">

	<h3>Please log-in</h3>

	<?php
	$form = $this->loginForm;
	$form->prepare();
	$form->setAttribute('action', $this->url('zfcuser/login'));
	$form->setAttribute('method', 'post');
	$form->setAttribute('class', 'form-inline');
	?>

	<?php echo $this->form()->openTag($form) ?>

		<?php if($form->getMessages()){?>
		<div class="alert alert-error">
		  <button type="button" class="close" data-dismiss="alert">&times;</button>
		  <strong>Warning!</strong>
		  <?php foreach($form->getMessages('identity') as $message){ ?>
		  	<?php echo $message?>
		  <?php }?>
		</div>
		<?php }?>

        <?php echo $this->formInput($form->get('identity')->setAttribute('class', 'input-small')) ?>

        <?php echo $this->formInput($form->get('credential')->setAttribute('class', 'input-small')) ?>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn')) ?>

	<?php echo $this->form()->closeTag() ?>

</div>